### ISSUE TITLE
iOS Bluetooth connection with ELM327 not working

### ISSUE THREAD

**Issue by Nightstep** [mickeyl/LTSupportAutomotive#1]
We've tried this sample with Bluetooth ELM327 adapter and it seems it's not working. Furthermore, iOS device can't see adapter at all (Settings->Bluetooth). But android device can. If you could do that with bluetooth ELM327() and iOS device, could you, please, provide version of adapter or any details will be appreciated. 

We've successfully connected with Wi-Fi ELM327 adapter with some changes in sample. So, is it possible to establish bluetooth connection between iOS and OBD2 adapter(maybe with help of CoreBluetooth)? Thanks.

**Comment by mickeyl** [comment]
This sounds like you have been trying to use a Bluetooth 2.x or 3.x adapter. These won't work with iOS as iOS only supports selected Bluetooth *profiles*, the serial profile not included. This is one area where Android is more flexible.

For iOS, you need a Bluetooth Low Energy (aka BTLE or Bluetooth 4.0) adapter. You can buy these on eBay or Amazon – two of those brands which I have tested personally are the CARISTA BLUETOOTH ADAPTER and LELINK BLUETOOTH LOW ENERGY ADAPTER.

**Comment by Nightstep** [comment]
Thanks a lot for information! We'll try it in a nearest future.
