### ISSUE TITLE
I want to know how it work

### ISSUE THREAD

**Issue by JRJian** [mickeyl/LTSupportAutomotive#18]
I have to start a app that communicate with vehicles using ELM327 adapters. I know nothing about it. I don't know how to start.

Do you have any turtorial about OBD programing?

Your library is very good, but i don't know what it means.

Like pidForMode1, pid or pidForFreezeFrameDTC. 

If i want to program OBD by myself, i need to lean more about it.

**Comment by NielsOkker** [comment]
Hi JRJian, 

I am not involved in this project, but do know a thing or two about OBD.

The Wiki about OBD is a great starting place: https://en.wikipedia.org/wiki/On-board_diagnostics.

About your questions. There are several services that an OBD-system has to offer, also called modes, the two fun ones are 1 and 2. The first is reading current data and the second mode is data that was 'freezed' when a MIL (Malfunction indication light, an icon on your dashboard) turned on.

Hope this helps!

**Comment by JRJian** [comment]
@NielsOkker Amazing! Thank you very much. It's very helpful. Now, i know what mode 1 and mode 2 mean. I'll read some OBD informations on wikipedia website. Than you again!
