### ISSUE TITLE
How to check engine light is on or off?

### ISSUE THREAD

**Issue by JRJian** [mickeyl/LTSupportAutomotive#19]
I haven't found the API which can read the engine light status.

**Comment by JRJian** [comment]
found it.
LTOBD2CommandELM327_IGNITION_STATUS

**Comment by mickeyl** [comment]
While LTOBD2CommandELM327_IGNITION_STATUS will definitely do what it's supposed to, please note that all the implementations of ELM327 that I know are having `ATIGN` wrongly implemented and will return `ON` as soon as the chip has power, i.e. no matter whether you really have ignition on or not. 

Unfortunately there doesn't seem to be a way to reliable tell this by looking at the OBD2 responses – at least I don't know any. The only thing you can tell is whether the engine is actually running or not (by checking RPM).

**Comment by JRJian** [comment]
@mickeyl Thanks for your comment. After reading your answer, I changed to use RPM to detect engine light status.
