### ISSUE TITLE
Can not connect to Wifi ELM 327

### ISSUE THREAD

**Issue by JackTedo** [mickeyl/LTSupportAutomotive#2]
I compiled and built the demo code into the iPhone, but the demo can not to connect to Wifi ELM 327. 

The Wifi ELM 327 I am using is https://www.amazon.com/KOBRA-Wireless-OBD-Scanner-Connects/dp/B01C3HAHCS/ref=sr_1_7_sspa?ie=UTF8&qid=1506971013&sr=8-7-spons&keywords=kobra+elm+327&psc=1

I tried other iOS apps, they could connect to this Wifi ELM 327. 

Do I need to make any changes to the demo code to make it works? Thank you very much.

**Comment by mickeyl** [comment]
This adapter should work. Did you make sure you're in the WiFi net of said ELM327 and got an address via DHCP or manual (e.g. 192.168.0.55 or so)? Can you paste the console output when running the demo?

**Comment by JackTedo** [comment]
Very sorry for the later.
I have a test with console output:
2017-12-22 10:42:19.700964-0500 Demo[1991:846254] [Accessibility] ****************** Loading GAX Client Bundle **************** 

![unadjustednonraw_thumb_3c](https://user-images.githubusercontent.com/27009133/34321274-fcc4fff8-e7d8-11e7-9fb0-24e172490bf5.jpg)
![unadjustednonraw_thumb_3d](https://user-images.githubusercontent.com/27009133/34321275-fccdb026-e7d8-11e7-9555-01ce9dda0967.jpg)

I read the https://github.com/mickeyl/LTSupportAutomotive/blob/master/Demo/ViewController.m file, it uses LTBTLESerialTransporter only, no wifi transporter related code found. So it means the demo code support bluetooth only. To support both wifi and bluetooth, need add wifi related code to demo/ViewController and may need user's input to determine if it is wifi or bluetooth obd. Am I correct? 

I will have another test when I get a bluetooth OBD later.

Thanks very much.

**Comment by JackTedo** [comment]
I have another test with following console output:

2017-12-29 10:51:09.774930-0600 Demo[386:45305] [Accessibility] ****************** Loading GAX Client Bundle ****************
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2Command:0x143d8a650 = 'ATD'> complete [61 ms] => 'OK'
-[ViewController onAdapterDidSendBytes:]_block_invoke (ViewController.m:355) OUT Ani in progress...
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2Command:0x143daf320 = 'ATZ'> complete [863 ms] => 'ATZ - ELM327 v1.5'
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2Command:0x143d3a980 = 'ATE0'> complete [109 ms] => 'ATE0 - OK'
-[ViewController onAdapterDidReceiveBytes:]_block_invoke (ViewController.m:373) IN Ani in progress...
-[ViewController onAdapterDidSendBytes:]_block_invoke (ViewController.m:355) OUT Ani in progress...
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2Command:0x143dada50 = 'ATRV'> complete [78 ms] => '12.4V'
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2Command:0x143daafa0 = 'ATSP0'> complete [118 ms] => 'OK'
-[ViewController onAdapterDidReceiveBytes:]_block_invoke (ViewController.m:373) IN Ani in progress...
-[ViewController onAdapterDidSendBytes:]_block_invoke (ViewController.m:355) OUT Ani in progress...
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2Command:0x143daf8f0 = 'ATE0'> complete [61 ms] => 'OK'
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2Command:0x143d573c0 = 'ATL1'> complete [63 ms] => 'OK'
-[ViewController onAdapterDidReceiveBytes:]_block_invoke (ViewController.m:373) IN Ani in progress...
-[ViewController onAdapterDidSendBytes:]_block_invoke (ViewController.m:355) OUT Ani in progress...
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2Command:0x143dbde80 = 'ATH1'> complete [62 ms] => 'OK'
-[ViewController onAdapterDidReceiveBytes:]_block_invoke (ViewController.m:373) IN Ani in progress...
-[ViewController onAdapterDidSendBytes:]_block_invoke (ViewController.m:355) OUT Ani in progress...
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2Command:0x143dc30d0 = 'ATI'> complete [67 ms] => 'ELM327 v1.5'
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2Command:0x143dbcae0 = 'ATS1'> complete [75 ms] => 'OK'
-[ViewController onAdapterDidReceiveBytes:]_block_invoke (ViewController.m:373) IN Ani in progress...
-[ViewController onAdapterDidSendBytes:]_block_invoke (ViewController.m:355) OUT Ani in progress...
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2Command:0x143daafa0 = 'ATIGN'> complete [61 ms] => 'ON'
-[ViewController onAdapterDidReceiveBytes:]_block_invoke (ViewController.m:373) IN Ani in progress...
-[ViewController onAdapterDidSendBytes:]_block_invoke (ViewController.m:355) OUT Ani in progress...
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2Command:0x143de3ff0 = '0100'> complete [3939 ms] => 'SEARCHING... - ...UNABLE TO CONNECT'
-[LTOBD2AdapterELM327 sendInitializationSequence]_block_invoke_4 (LTOBD2AdapterELM327.m:126) Did not get a valid response, trying slow initialization path...
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2CommandELM327_TRY_PROTOCOL:0x143dc80d0 = 'ATTP1'> complete [62 ms] => 'OK'
-[ViewController onAdapterDidReceiveBytes:]_block_invoke (ViewController.m:373) IN Ani in progress...
-[ViewController onAdapterDidSendBytes:]_block_invoke (ViewController.m:355) OUT Ani in progress...
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2Command:0x143dbcae0 = '0100'> complete [371 ms] => 'NO DATA'
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2CommandELM327_TRY_PROTOCOL:0x1459112e0 = 'ATTP2'> complete [73 ms] => 'OK'
-[ViewController onAdapterDidReceiveBytes:]_block_invoke (ViewController.m:373) IN Ani in progress...
-[ViewController onAdapterDidSendBytes:]_block_invoke (ViewController.m:355) OUT Ani in progress...
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2Command:0x145900ce0 = '0100'> complete [373 ms] => 'NO DATA'
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2CommandELM327_TRY_PROTOCOL:0x143d8a650 = 'ATTP3'> complete [76 ms] => 'OK'
-[ViewController onAdapterDidReceiveBytes:]_block_invoke (ViewController.m:373) IN Ani in progress...
-[ViewController onAdapterDidSendBytes:]_block_invoke (ViewController.m:355) OUT Ani in progress...
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2Command:0x143de3ff0 = '0100'> complete [2777 ms] => 'BUS INIT: ...ERROR'
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2CommandELM327_TRY_PROTOCOL:0x143dc80d0 = 'ATTP4'> complete [65 ms] => 'OK'
-[ViewController onAdapterDidReceiveBytes:]_block_invoke (ViewController.m:373) IN Ani in progress...
-[ViewController onAdapterDidSendBytes:]_block_invoke (ViewController.m:355) OUT Ani in progress...
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2Command:0x143d8a650 = '0100'> complete [2773 ms] => 'BUS INIT: ...ERROR'
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2CommandELM327_TRY_PROTOCOL:0x143de3ff0 = 'ATTP5'> complete [72 ms] => 'OK'
-[ViewController onAdapterDidReceiveBytes:]_block_invoke (ViewController.m:373) IN Ani in progress...
-[ViewController onAdapterDidSendBytes:]_block_invoke (ViewController.m:355) OUT Ani in progress...
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2Command:0x143dc80d0 = '0100'> complete [503 ms] => 'BUS INIT: ERROR'
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2CommandELM327_TRY_PROTOCOL:0x145900ce0 = 'ATTP6'> complete [62 ms] => 'OK'
-[ViewController onAdapterDidReceiveBytes:]_block_invoke (ViewController.m:373) IN Ani in progress...
-[ViewController onAdapterDidSendBytes:]_block_invoke (ViewController.m:355) OUT Ani in progress...
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2Command:0x14590bc80 = '0100'> complete [90 ms] => 'NO DATA'
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2CommandELM327_TRY_PROTOCOL:0x143dc30d0 = 'ATTP7'> complete [63 ms] => 'OK'
-[ViewController onAdapterDidReceiveBytes:]_block_invoke (ViewController.m:373) IN Ani in progress...
-[ViewController onAdapterDidSendBytes:]_block_invoke (ViewController.m:355) OUT Ani in progress...
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2Command:0x143d8a650 = '0100'> complete [89 ms] => 'NO DATA'
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2CommandELM327_TRY_PROTOCOL:0x143dc30d0 = 'ATTP8'> complete [63 ms] => 'OK'
-[ViewController onAdapterDidReceiveBytes:]_block_invoke (ViewController.m:373) IN Ani in progress...
-[ViewController onAdapterDidSendBytes:]_block_invoke (ViewController.m:355) OUT Ani in progress...
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2Command:0x143dbcae0 = '0100'> complete [91 ms] => 'NO DATA'
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2CommandELM327_TRY_PROTOCOL:0x143de3ff0 = 'ATTP9'> complete [64 ms] => 'OK'
-[ViewController onAdapterDidReceiveBytes:]_block_invoke (ViewController.m:373) IN Ani in progress...
-[ViewController onAdapterDidSendBytes:]_block_invoke (ViewController.m:355) OUT Ani in progress...
-[LTOBD2AdapterInternalCommand didCompleteResponse:protocol:protocolType:] (LTOBD2Adapter.m:58) <LTOBD2Command:0x143dc30d0 = '0100'> complete [89 ms] => 'NO DATA'

**Comment by lygialiem** [comment]
@JackTedo in this library, where can I set address to connect to ELM327 devices through wifi?
