### ISSUE TITLE
Trouble codes parsing array index why start with 1

### ISSUE THREAD

**Issue by JRJian** [mickeyl/LTSupportAutomotive#20]
`NSRange codeRange = NSMakeRange(1, bytes.count-1);`
`NSArray<NSNumber*>* codeBytes = [bytes subarrayWithRange:codeRange];`

The returned result is different from other OBD apps.（Such as Auto Doctor、ELM327...）

If I change the index to 0，the result will be consistent.

**Comment by mickeyl** [comment]
Let me show you an example, here's communication over protocol 7:

I ask for `03` and get the following `rawResponse`:

```
(lldb) po self.rawResponse
<__NSArrayM 0x28150cbd0>(
18DAF110100A430401100148,
18DAF1102101700210000000
)

```

Stripping the ECU IDs and reassembling the fragments gives me the following `cookedResponse`:

```
(lldb) po self.cookedResponse
{
    10 =     (
        4,
        1,
        16,
        1,
        72,
        1,
        112,
        2,
        16,
        0,
        0,
        0
    );
}
```

We are seeing ECU #10 responding with 12 bytes. To my knowledge, every DTC is encoded as 2 bytes and the first byte of the whole response to `03` and `07` is the actual number of encountered DTCs, i.e. in this example we are seeing 4 DTCs where as the actual values are P0110, P0148, P0170, and P0210.

If you think this is wrong, could you show me example data from your car?

**Comment by mukulpandey57** [comment]
Hello @mickeyl , I am getting "P2800" from this Library, but other apps or wired scanner reads "P1628". 
Please suggest or If I'll change the index to 0 will fix it as above mentioned by @JRJian 
In  NSRange codeRange = NSMakeRange(1, bytes.count-1);
NSArray<NSNumber*>* codeBytes = [bytes subarrayWithRange:codeRange];
![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/8499425/90129257-efb18980-dd85-11ea-87fa-8fbad3231a3d.png)
screen shot of wired scanner.

**Comment by mukulpandey57** [comment]
NSRange codeRange = NSMakeRange(1, bytes.count-1);
NSArray<NSNumber*>* codeBytes = [bytes subarrayWithRange:codeRange];

@JRJian  @thdankert @mickeyl , This code is correct or have to change the RangeIndex to 0?
Please Help. (Not getting ABS fault codes specifically "U0102" )

**Comment by mickeyl** [comment]
Thanks for opening this issue, I think you are up to something. My implementation of the DTC parsing code is based on SAE J1979_201408, which is the reference, but I may have mixed up some of the tables depicted in there (granted, it's quite a confusing spec in some places). I have developed the DTC-implementation against an OBD2 Simulator (since I do not possess so many cars with actual failures), it might be possible that this Simulator has a broken implementation of the DTC answer. I will double check with the spec later this week and report ASAP.

**Comment by mickeyl** [comment]
I may have spoken too soon. Upon my inquiry, the simulator developer just got back to me and claims that for all CAN-protocols, the answer to `03` _has_ to report the number of DTCs before the actual codes. Can anyone confirm or deny that?

**Comment by bilics** [comment]
> I may have spoken too soon. Upon my inquiry, the simulator developer just got back to me and claims that for all CAN-protocols, the answer to `03` _has_ to report the number of DTCs before the actual codes. For all other protocols, this number will be omitted.
> 
> Can anyone confirm or deny that?

Hi! Can you share the simulator you used? Is it possible to run the simulator on a Mac and expose it through bluetooth?

Thanks!
