### ISSUE TITLE
How to connect with Wifi ELM327?

### ISSUE THREAD

**Issue by JRJian** [mickeyl/LTSupportAutomotive#21]
The demo I tried is only can connect with bluetooth mode.

When I connect to a Wifi ELM327 and get the ip address, open the app. Found that it is always in search status.

**Comment by JRJian** [comment]
I programed a socket communication to connect to the WiFi ELM327 and it work correctly.

**Comment by tuantran87** [comment]
JRJian, can you help me to config connect with Wifi ELM327? I have a issue about it. Thanks

**Comment by maximd33** [comment]
@JRJian , @tuantran87 any reference for implementation?
