### ISSUE TITLE
LTOBD2PID_FUEL_TANK_LEVEL_2F Command - Response "No data"

### ISSUE THREAD

**Issue by veron3001** [mickeyl/LTSupportAutomotive#24]
I have been using this library to get the speed of a car via Bluetooth (LTOBD2PID_VEHICLE_SPEED_0D) and it works great. Now I need to get the tank fuel - LTOBD2PID_FUEL_TANK_LEVEL_2F - but I get response: "No data". I tried with 2 different OBD2 dongles on 2 different cars and the result is the same. I am trying to get it the same way I get the speed. Should there be some difference? What can be wrong?
Edit: I checked also with the iOS demo project and the result there is also "No data" for Fuel tank level. Why could this happen? I noticed that also for some other PIDs the result is "No data".

**Comment by mickeyl** [comment]
I'm afraid there's not much you can do about it. As per the SAE standard, apart from the management PIDs (0100, 0120, 0140, 0160, etc.), the implementation of the concrete PIDs is optional and I have seen very little vehicles actually deliver a response to 012F.

That said, can you check what 0120 for one of the vehicles returns?
