### ISSUE TITLE
Reading DTCs

### ISSUE THREAD

**Issue by natethegreate** [mickeyl/LTSupportAutomotive#31]
I am having some issues regarding reading DTCs through mode 03, 07, and 0A. 

When compared to a wired OBD reader, we only read from one of all available locations.
Pictured below is a wired reader with DTCs on the ABS and ECM modules, along with the OBDII/EOBD. We are only reading codes from the OBDII/EOBD, and not on the ABS nor ECM, nor TCM if applicable. 

![image](https://user-images.githubusercontent.com/36290465/90898851-b502af00-e38c-11ea-88e8-686a60990a2a.png)

I am using a compatible adapter, and using some apps on the App Store I have been able to read from the ABS module using my adapter.

I am wondering if anything like this has been done with this library

**Comment by mukulpandey57** [comment]
@thdankert  Please go-through with this, may be you can identify the issue.

**Comment by mickeyl** [comment]
With #20 being closed, the DTC reporting should be in sync with other readers and apps now. Please reopen if there is still something broken.
