### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by nilsmassing** [mickeyl/LTSupportAutomotive#34]
Hello Mickey,

I'm a student from Germany and me and a small team of colleagues is working on a simple Dashboard App for iOS. It's just a small project for university and we are all not that deep into programming. We've tried to add your library with Cocoapods and used your example project to test the connection with an OBDLink MX+ Adapter. Unfortunately, we can't get the app to connect to our Adapter or get any sign of connectivity. The build succeeds without issues and we tried several things like adding a Bluetooth Usage Key in Info.plist but nothing is working out for us.
Can you or someone help us to find the problem? Would be really appreciated. 

Best Regards

**Comment by CarDr-com** [comment]
Use LTSupportAutomative Framework in your app instead of cocoapods it will work fine like sample code, there seems to be a bug in Pod file.
