### ISSUE TITLE
Crash when adapter state changed 

### ISSUE THREAD

**Issue by Ravish1** [mickeyl/LTSupportAutomotive#41]
@mickeyl The libraray is working fine getting all the required data but sometime when adater state changed ,I am getting crash with odd logs .Whenever you have have time can you please check.Here the log which i am getting during crash -
Unhandeld adapter state OBD2AdapterStateReady

thread #53, queue = 'LTBTLESerialTransporter', stop reason = EXC_BAD_ACCESS (code=1, address=0x2ce66b20)
frame #0: 0x0000000198499880 libobjc.A.dylibobjc_retain + 16 libobjc.A.dylibobjc_retain:
-> 0x198499880 <+16>: ldrb w10, [x9, #0x20]
0x198499884 <+20>: tbz w10, #0x2, 0x1984998b4 ; <+68>
0x198499888 <+24>: tbz w8, #0x0, 0x1984998dc ; <+108>
0x19849988c <+28>: mov x9, #0x200000000000
Target 0: (Runner) stopped.

**Comment by mickeyl** [comment]
Could you post a complete log + traceback? I can't seem to reproduce this here.

The output "Unhandeld adapter state …" itself does not point to a problem.

**Comment by Ravish1** [comment]
Thanks for the reply.I have performed disconnect method oncee it diconnected and trying to connect again it crashed with the above logs.Until disconnect there is no crash
