### ISSUE TITLE
Documentation refers to Swift-UDS which cannot be found on GitHub

### ISSUE THREAD

**Issue by jasonthenderson** [mickeyl/LTSupportAutomotive#47]
Is there any plan to make Swift-UDS available?  I would LOVE to try it out if so, I'm working on a hobby project using iPad Swift Playgrounds so I can only easily include Swift-based libraries and this would be huge.    Just finished getting some BLE lithium batteries hooked up to my app, which was a lot of fun in itself ;)

Thank you!

**Comment by mickeyl** [comment]
I'm sorry, for business reasons, I had to pull Swift-UDS and continue to develop it in private. It's now a much more capable, but proprietary library (including UDS, KWP, CCP, XCM, HSFZ, etc.) for which I'm working on a commercially licensable SDK.
