### ISSUE TITLE
How to read odometer from OBD2?

### ISSUE THREAD

**Issue by tigermobiledev** [mickeyl/LTSupportAutomotive#50]

**Comment by mlawlerau** [comment]
You can try service 01, PID A6 which is a standard PID. But not every manufacturer will respond to this PID, but it seems mandatory for cars after 2019.

**Comment by mickeyl** [comment]
This has now been implemented as per https://github.com/mickeyl/LTSupportAutomotive/commit/784c654934627a8845bb04515c3fd6108faddedc
