### ISSUE TITLE
Bug in LTOBD2PID_DISTANCE_SINCE_DTC_CLEARED_31

### ISSUE THREAD

**Issue by pegan** [mickeyl/LTSupportAutomotive#51]
The `-(NSString*)formattedResponse` method in `@implementation LTOBD2PID_DISTANCE_SINCE_DTC_CLEARED_31` uses `-(NSString*)formatSingleByteDoubleValueWithString:(NSString*)formatString offset:(double)offset factor:(double)factor`

It should use instead: `-(NSString*)formatTwoByteDoubleValueWithString:(NSString*)formatString offset:(double)offset factor:(double)factor` with `factor: 1`

Source: https://en.wikipedia.org/wiki/OBD-II_PIDs 
The formula for *Distance traveled since codes cleared*: 256A + B

**Comment by mickeyl** [comment]
Indeed. Thanks @pegan.
