### ISSUE TITLE
Wrong conversion of DTC codes to ASCII

### ISSUE THREAD

**Issue by thdankert** [mickeyl/LTSupportAutomotive#6]
When DTCs are received (eg. as a result of a mode 03 request), they are converted from the native ELM327 format to SAE format, as defined in the ELM data sheet.

However, this conversion does not correctly convert received DTCs with hex characters.
The error lies in function `-(NSString*)dtcCodeForA:(uint)A B:(uint)B`, which tries to convert all received values back to ASCII numbers.

Example:
DTC = `P2B4A` is received via ELM327 as `2B4A`, but the function returns the following:
```
[pid dtcCodeForA:0x2B B:0x4A] = "P2;4:"
```

`;` and `:` are `A` and `B` (ASCII hex lower nibble), respectively.

I'll provide a push request shortly - the received characters should be passed through as-is.

**Comment by mickeyl** [comment]
Thanks for reporting this issue! Would it be possible to add a log from a car that returns such a DTC?

**Comment by thdankert** [comment]
Hi mickeyl,

I don't have the log available (it's from a yet unreleased car), but when debugging this issue, I used your "OBD II Expert" app in simulator mode and used the vehicle "Mercedes-Benz GL-Class...".
This also produced DTCs with hex codes in them.

Please see the corresponding pull request for more details.

**Comment by JRJian** [comment]
@mickeyl Why did you subarray from index 1?

`NSRange codeRange = NSMakeRange(1, bytes.count-1);`
`NSArray<NSNumber*>* codeBytes = bytes subarrayWithRange:codeRange];`

The returned result is different from other OBD apps.（Such as Auto Doctor、ELM327...）

If I change the index to 2，the result will be consistent.
